/**
 * Seed script — THINK-AI ATS
 * Creates 11 AI engineering roles (L5–L15) and 22 Saudi national candidate profiles
 * representing engineers with AI experience at top global tech companies, based in Riyadh.
 *
 * Run: node scripts/seed.mjs
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ─── Level → Role title mapping ────────────────────────────────────────────────
const LEVEL_TITLES = {
  L5:  "Associate AI Engineer",
  L6:  "AI Engineer",
  L7:  "Senior AI Engineer",
  L8:  "Lead AI Engineer",
  L9:  "Staff AI Engineer",
  L10: "Senior Staff AI Engineer",
  L11: "Principal AI Engineer",
  L12: "Senior Principal Engineer",
  L13: "Distinguished Engineer",
  L14: "Engineering Fellow",
  L15: "Senior Fellow / Chief AI Architect",
};

// ─── Jobs (L5–L15, software + hardware AI) ─────────────────────────────────────
const JOBS = [
  {
    title: "Associate AI Software Engineer",
    level: "L5",
    department: "Engineering",
    location: "Riyadh, KSA",
    jobType: "full-time",
    specialty: "Machine Learning / Python",
    description: "Entry-level AI engineering role. You will build and integrate ML models into production pipelines under senior guidance. Core stack: Python, PyTorch/TensorFlow, Docker, REST APIs.",
    requirements: ["Python (3+ years)", "ML fundamentals", "Git", "Docker basics", "Strong mathematics (linear algebra, probability)"],
    targetCountries: ["Saudi Arabia", "Egypt", "Jordan"],
    minYearsExp: 2, maxYearsExp: 4, preferAIExp: true, headcount: 3, status: "open",
  },
  {
    title: "AI Engineer — Computer Vision",
    level: "L6",
    department: "Engineering",
    location: "Riyadh, KSA",
    jobType: "full-time",
    specialty: "Computer Vision",
    description: "Design and deploy computer vision models for real-world applications including object detection, segmentation and visual inspection systems for industrial and smart-city clients.",
    requirements: ["Python", "OpenCV", "PyTorch", "YOLO / Detectron2", "3+ years computer vision", "CUDA/GPU optimisation"],
    targetCountries: ["Saudi Arabia", "UAE", "Egypt", "Pakistan", "India"],
    minYearsExp: 3, maxYearsExp: 6, preferAIExp: true, headcount: 2, status: "open",
  },
  {
    title: "AI Engineer — Embedded Systems",
    level: "L6",
    department: "Hardware Engineering",
    location: "Riyadh, KSA",
    jobType: "full-time",
    specialty: "Embedded AI / Edge Computing",
    description: "Deploy neural networks on edge hardware (Jetson, FPGA, MCUs). Work across the SW/HW boundary to achieve low-power, real-time AI inference for THINK-AI's hardware products.",
    requirements: ["C/C++", "Python", "TensorRT / ONNX", "RTOS", "FPGA or ASIC experience a plus", "3–6 years embedded systems"],
    targetCountries: ["Saudi Arabia", "UAE", "India", "Pakistan"],
    minYearsExp: 3, maxYearsExp: 6, preferAIExp: true, headcount: 2, status: "open",
  },
  {
    title: "Senior AI Engineer — NLP & LLMs",
    level: "L7",
    department: "Engineering",
    location: "Riyadh, KSA",
    jobType: "full-time",
    specialty: "NLP / Large Language Models",
    description: "Lead NLP/LLM product development — fine-tuning, RAG architectures, Arabic language model adaptation, and LLM-powered product features. Own technical design for language AI systems.",
    requirements: ["Transformers / HuggingFace", "LLM fine-tuning (LoRA, QLoRA)", "RAG pipelines", "Arabic NLP a strong plus", "5–8 years NLP/ML", "LangChain / LlamaIndex"],
    targetCountries: ["Saudi Arabia", "Egypt", "Jordan", "Lebanon", "Tunisia"],
    minYearsExp: 5, maxYearsExp: 8, preferAIExp: true, headcount: 2, status: "open",
  },
  {
    title: "Senior Embedded AI Hardware Engineer",
    level: "L7",
    department: "Hardware Engineering",
    location: "Riyadh, KSA",
    jobType: "full-time",
    specialty: "Embedded AI / FPGA / ASIC",
    description: "Design AI accelerator blocks and integrate them into THINK-AI's proprietary hardware. RTL design, model quantisation to run on custom silicon, and co-design with software teams.",
    requirements: ["RTL / Verilog / VHDL", "FPGA (Xilinx/Intel)", "Model quantisation", "Hardware-software co-design", "5–8 years embedded hardware"],
    targetCountries: ["Saudi Arabia", "UAE", "India", "Pakistan", "UK"],
    minYearsExp: 5, maxYearsExp: 9, preferAIExp: true, headcount: 1, status: "open",
  },
  {
    title: "Lead AI Engineer — MLOps & Platform",
    level: "L8",
    department: "Engineering",
    location: "Riyadh, KSA",
    jobType: "full-time",
    specialty: "MLOps / AI Platform",
    description: "Own the AI platform end-to-end: feature stores, model registries, CI/CD for ML, monitoring and drift detection. Enable 10+ data scientists to ship models faster. You define the platform strategy.",
    requirements: ["MLflow / Weights & Biases / Kubeflow", "Kubernetes", "Terraform", "Python", "7–10 years engineering", "3+ years MLOps", "Strong system design"],
    targetCountries: ["Saudi Arabia", "UAE", "India", "UK", "USA", "Canada"],
    minYearsExp: 7, maxYearsExp: 10, preferAIExp: true, headcount: 1, status: "open",
  },
  {
    title: "Lead Hardware AI Architect — ASIC/FPGA",
    level: "L8",
    department: "Hardware Engineering",
    location: "Riyadh, KSA",
    jobType: "full-time",
    specialty: "AI Chip / ASIC Architecture",
    description: "Lead the architecture of THINK-AI's next-gen AI accelerator chip. Drive micro-architecture decisions, dataflow analysis and tapeout planning. Collaborate with EDA, software and product teams.",
    requirements: ["Chip micro-architecture", "Dataflow / systolic arrays", "RTL ownership", "TSMC/GlobalFoundries tape-out experience", "8–11 years hardware design", "AI workload profiling"],
    targetCountries: ["Saudi Arabia", "USA", "UK", "Taiwan", "South Korea", "Germany"],
    minYearsExp: 7, maxYearsExp: 11, preferAIExp: true, headcount: 1, status: "open",
  },
  {
    title: "Staff AI Engineer — AI Research & Applied Science",
    level: "L9",
    department: "Research",
    location: "Riyadh, KSA",
    jobType: "full-time",
    specialty: "AI Research / Applied Science",
    description: "Bridge research and production. Define the next 12-month research agenda, publish externally, and translate breakthroughs into shippable products. Own multiple active research tracks simultaneously.",
    requirements: ["PhD or equivalent research record", "Publication history (NeurIPS / ICLR / CVPR / ACL)", "9–12 years ML experience", "Mentorship of junior researchers", "Strong Python + C++"],
    targetCountries: ["Saudi Arabia", "USA", "UK", "Germany", "Canada", "Egypt"],
    minYearsExp: 9, maxYearsExp: 12, preferAIExp: true, headcount: 1, status: "open",
  },
  {
    title: "Senior Staff AI Engineer — AI Systems Architecture",
    level: "L10",
    department: "Engineering",
    location: "Riyadh, KSA",
    jobType: "full-time",
    specialty: "Distributed AI Systems",
    description: "Define the technical architecture for THINK-AI's AI inference infrastructure at scale. Solve cross-cutting problems affecting multiple teams. Drive company-wide technical standards for AI systems.",
    requirements: ["10–13 years engineering", "Distributed systems at scale", "GPU cluster management", "Strong systems thinking", "C++ and Python mastery", "Open to serving as technical mentor across org"],
    targetCountries: ["Saudi Arabia", "USA", "UK", "Canada", "Germany", "India"],
    minYearsExp: 10, maxYearsExp: 13, preferAIExp: true, headcount: 1, status: "open",
  },
  {
    title: "Principal AI Engineer",
    level: "L11",
    department: "Engineering",
    location: "Riyadh, KSA",
    jobType: "full-time",
    specialty: "AI Strategy / Technical Leadership",
    description: "Define multi-year technical strategy for AI software. Represent THINK-AI externally (conferences, standards bodies). Identify and incubate new AI capabilities that become product lines.",
    requirements: ["12–14 years experience", "Proven large-scale AI system ownership", "External technical presence (talks, papers, open-source)", "Arabic language a bonus", "Deep expertise in ≥2 AI domains"],
    targetCountries: ["Saudi Arabia", "USA", "UK", "UAE", "Canada"],
    minYearsExp: 11, maxYearsExp: 14, preferAIExp: true, headcount: 1, status: "open",
  },
  {
    title: "Engineering Fellow / Distinguished AI Engineer",
    level: "L13",
    department: "Engineering",
    location: "Riyadh, KSA",
    jobType: "full-time",
    specialty: "AI Architecture / Foundational Research",
    description: "Peer-level with VP Engineering. Set 5-year technical vision. Work directly with the founder on strategic bets. THINK-AI's highest individual contributor role — equivalent authority to a business unit leader.",
    requirements: ["13–15+ years", "Internationally recognised AI expertise", "Deep technical credibility across SW and HW AI", "Track record of building and shipping foundational AI systems", "Willing to relocate to Riyadh"],
    targetCountries: ["Saudi Arabia", "USA", "UK", "Canada", "Germany", "France", "UAE"],
    minYearsExp: 13, maxYearsExp: 20, preferAIExp: true, headcount: 1, status: "open",
  },
];

// ─── Candidates — Saudi nationals, Riyadh-based, AI exp at top tech companies ─
const CANDIDATES = [
  // ── Software AI ──────────────────────────────────────────────────────────────
  {
    name: "Ahmed Al-Zahrani",
    email: "ahmed.alzahrani@gmail.com",
    currentRole: "Senior ML Engineer",
    currentCompany: "Google Arabia",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 7,
    specialty: "Computer Vision / Deep Learning",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Google", "SDAIA"],
    skills: ["PyTorch", "TensorFlow", "YOLO", "Kubernetes", "Python", "CUDA", "GCP"],
    education: "BSc Computer Science — KAUST",
    languages: ["Arabic", "English"],
    notes: "7 years at Google Arabia working on computer vision for Maps and Search. Led the Arabic OCR initiative. Holds 2 patents on image recognition. Active speaker at Saudi AI Summit.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/ahmed-alzahrani-ml",
  },
  {
    name: "Mohammed Al-Ghamdi",
    email: "m.alghamdi@outlook.com",
    currentRole: "Applied AI Research Scientist",
    currentCompany: "Microsoft Research (Riyadh Hub)",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 10,
    specialty: "NLP / Large Language Models",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Microsoft", "Anthropic (advisor)", "SDAIA"],
    skills: ["Transformers", "HuggingFace", "Azure OpenAI", "Python", "Arabic NLP", "RLHF", "LLM fine-tuning"],
    education: "PhD NLP — King Abdullah University of Science and Technology (KAUST)",
    languages: ["Arabic", "English", "French"],
    notes: "10 years in NLP; co-authored AraBERT-v2 and published at ACL 2023. Leads Microsoft's Arabic language model division in Riyadh. Fluent in English, Arabic, and French. Advised SDAIA on National AI Strategy 2030.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/mohammed-alghamdi-nlp",
  },
  {
    name: "Omar Al-Qahtani",
    email: "omar.qahtani@gmail.com",
    currentRole: "Computer Vision Engineer",
    currentCompany: "Huawei Technologies Arabia",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 5,
    specialty: "Computer Vision / Edge AI",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Huawei"],
    skills: ["OpenCV", "PyTorch", "TensorRT", "ONNX", "MindSpore", "Python", "C++", "Edge deployment"],
    education: "MSc Electrical Engineering — King Fahd University (KFUPM)",
    languages: ["Arabic", "English", "Mandarin (basic)"],
    notes: "5 years at Huawei building edge CV models for smart surveillance and autonomous vehicles. Worked with the Kirin NPU team in Shenzhen for 18 months. Strong TensorRT optimisation skills.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/omar-alqahtani-cv",
  },
  {
    name: "Khalid Al-Maliki",
    email: "khalid.maliki@proton.me",
    currentRole: "MLOps Senior Engineer",
    currentCompany: "Amazon Web Services (MENA)",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 8,
    specialty: "MLOps / AI Platform",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Amazon", "STC Digital"],
    skills: ["SageMaker", "Kubeflow", "Terraform", "Kubernetes", "Python", "MLflow", "Apache Kafka", "Spark"],
    education: "BSc Software Engineering — King Saud University",
    languages: ["Arabic", "English"],
    notes: "8 years in cloud ML. Built the MLOps platform for Amazon's MENA government cloud customers. Previously at STC Digital. Strong Kubernetes and Terraform. Managed a 6-person MLOps team.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/khalid-almaliki-mlops",
  },
  {
    name: "Faisal Al-Otaibi",
    email: "faisal.otaibi@gmail.com",
    currentRole: "NLP Engineer",
    currentCompany: "IBM Technology — Riyadh",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 6,
    specialty: "NLP / Conversational AI",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["IBM", "Lucidya"],
    skills: ["Watson NLU", "spaCy", "Python", "Arabic dialect recognition", "RAG", "LangChain", "FastAPI", "Docker"],
    education: "BSc Computer Science — University of Riyadh",
    languages: ["Arabic", "English"],
    notes: "6 years in Arabic NLP. Built IBM Watson Arabic dialect classifier used by 12 KSA government agencies. Previously at Lucidya (Saudi social listening AI company). Strong Arabic text preprocessing expertise.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/faisal-alotaibi-nlp",
  },
  {
    name: "Salman Al-Dossari",
    email: "s.dossari@icloud.com",
    currentRole: "AI Platform Engineer",
    currentCompany: "SAP Innovation Center — Riyadh",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 9,
    specialty: "AI Platform / MLOps",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["SAP", "SDAIA", "ELM"],
    skills: ["SAP BTP", "Python", "Feature Store", "Kubeflow", "MLflow", "Azure ML", "Databricks", "SQL"],
    education: "MSc Information Systems — KFUPM",
    languages: ["Arabic", "English", "German (basic)"],
    notes: "9 years building enterprise AI platforms. Led SAP's AI Centre of Excellence for KSA and Gulf. Previously worked with SDAIA on the Zakat AI project and ELM on national identity AI systems. Team lead of 8 engineers.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/salman-aldossari-ai",
  },
  {
    name: "Turki Al-Harbi",
    email: "turki.harbi@gmail.com",
    currentRole: "Deep Learning Engineer",
    currentCompany: "NVIDIA — Gulf",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 4,
    specialty: "Deep Learning / GPU Computing",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["NVIDIA", "Mozn"],
    skills: ["CUDA", "TensorRT", "PyTorch", "Python", "C++", "cuDNN", "Triton Inference Server", "GPU profiling"],
    education: "BSc Computer Engineering — KAUST",
    languages: ["Arabic", "English"],
    notes: "4 years at NVIDIA as deep learning developer advocate and engineer for Gulf region. Certified NVIDIA DLI instructor. Previously at Mozn (Saudi AI startup). Expert in GPU memory optimisation and CUDA kernel writing.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/turki-alharbi-nvidia",
  },
  {
    name: "Bandar Al-Mutairi",
    email: "bandar.mutairi@gmail.com",
    currentRole: "Senior Machine Learning Engineer",
    currentCompany: "Meta Platforms — MENA",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 8,
    specialty: "Recommendation Systems / ML",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Meta", "STC Digital"],
    skills: ["PyTorch", "DLRM", "Spark", "Presto", "Python", "Scala", "distributed training", "A/B testing"],
    education: "MSc Machine Learning — Carnegie Mellon University (remote + Riyadh)",
    languages: ["Arabic", "English"],
    notes: "8 years in recommendation systems and ranking. Led the Arabic content ranking model for Meta in MENA — 180M users. Previously at STC Digital building telco churn prediction models. Strong distributed training background.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/bandar-almutairi-ml",
  },
  {
    name: "Majed Al-Anazi",
    email: "majed.anazi@outlook.com",
    currentRole: "AI Research Lead",
    currentCompany: "Aramco Digital",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 10,
    specialty: "Industrial AI / Computer Vision",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Aramco Digital", "Schlumberger AI", "IBM"],
    skills: ["PyTorch", "Anomaly Detection", "Industrial IoT", "Digital Twins", "Python", "Time-series ML", "Azure", "GCP"],
    education: "PhD Petroleum Engineering AI — King Abdullah University",
    languages: ["Arabic", "English"],
    notes: "10 years at Aramco Digital leading AI research for upstream operations. Owns the visual inspection AI platform deployed across 28 refineries. Published 7 papers on industrial AI. External advisor at IBM for energy-sector AI.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/majed-alanazi-aramco",
  },
  {
    name: "Rayan Al-Saud",
    email: "rayan.alsaud@gmail.com",
    currentRole: "NLP Research Scientist",
    currentCompany: "Oracle Cloud AI — Riyadh",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 6,
    specialty: "NLP / Information Extraction",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Oracle", "SDAIA", "Lucidya"],
    skills: ["NLP", "information extraction", "BERT", "GPT fine-tuning", "Python", "Arabic language models", "Oracle OCI", "REST APIs"],
    education: "MSc Computer Science — King Saud University",
    languages: ["Arabic", "English"],
    notes: "6 years in Arabic NLP and information extraction. Built Oracle's Arabic document processing pipeline used by 35 Saudi ministries. Former NLP lead at Lucidya. Published at EMNLP 2022.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/rayan-alsaud-nlp",
  },
  {
    name: "Ziad Al-Barrak",
    email: "ziad.barrak@proton.me",
    currentRole: "MLOps Platform Lead",
    currentCompany: "Cisco Systems — KSA",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 9,
    specialty: "MLOps / DevSecOps AI",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Cisco", "Palantir MENA", "ELM"],
    skills: ["Kubernetes", "Terraform", "Helm", "MLflow", "Apache Airflow", "Python", "Go", "CI/CD", "Network AI"],
    education: "BSc Network Engineering — Prince Sultan University",
    languages: ["Arabic", "English"],
    notes: "9 years MLOps and network AI. Built Cisco's ML pipeline platform for KSA telecom clients. Consulted for Palantir MENA on government AI deployments. Led ELM's DevOps-to-MLOps transformation. Certified Kubernetes administrator.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/ziad-albarrak-mlops",
  },
  {
    name: "Abdulrahman Al-Osaimi",
    email: "ar.osaimi@gmail.com",
    currentRole: "Principal AI Engineer",
    currentCompany: "Mozn — Riyadh",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 12,
    specialty: "AI Strategy / FinTech AI",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Mozn", "C3.ai", "STC Digital", "Alibaba Cloud"],
    skills: ["Python", "ML system design", "risk models", "fraud detection", "architecture review", "team building", "Arabic NLP"],
    education: "MSc Artificial Intelligence — University of Edinburgh",
    languages: ["Arabic", "English"],
    notes: "12 years in AI, currently Principal Engineer at Mozn (Saudi AI fintech). Architected fraud detection systems processing 4M transactions/day. Previously C3.ai MENA lead and Alibaba Cloud AI consultant. Manages team of 9 engineers.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/ar-osaimi-principal",
  },
  // ── Hardware AI ──────────────────────────────────────────────────────────────
  {
    name: "Abdullah Al-Shehri",
    email: "a.shehri@gmail.com",
    currentRole: "Principal FPGA AI Engineer",
    currentCompany: "Intel Programmable Solutions — Riyadh",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 12,
    specialty: "FPGA / AI Accelerators",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Intel", "Qualcomm MENA", "NEOM Tech"],
    skills: ["Verilog", "VHDL", "Intel Quartus", "Xilinx Vivado", "HLS", "neural network quantisation", "PCIe", "OpenCL FPGA"],
    education: "MSc Electronic Engineering — Imperial College London",
    languages: ["Arabic", "English"],
    notes: "12 years FPGA design, focusing on AI acceleration since 2019. Led Intel's FPGA AI demonstration at GITEX 2023. Worked with NEOM Tech on autonomous mobility AI hardware. Holds 3 patents on FPGA-accelerated matrix multiplication.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/abdullah-alshehri-fpga",
  },
  {
    name: "Nawaf Al-Rashid",
    email: "nawaf.rashid@outlook.com",
    currentRole: "Embedded AI Systems Engineer",
    currentCompany: "Qualcomm Technologies — Riyadh",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 11,
    specialty: "Embedded AI / Snapdragon NPU",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Qualcomm", "ARM Limited", "Huawei"],
    skills: ["Snapdragon AI SDK", "QNN", "ONNX Runtime", "C++", "RTOS", "TFLite", "model quantisation", "int8/int4", "power analysis"],
    education: "BSc Electrical Engineering — KFUPM (First Class Honours)",
    languages: ["Arabic", "English"],
    notes: "11 years at Qualcomm on AI inference for Snapdragon chips. Ported 40+ production neural networks to Snapdragon NPU for MENA OEM partners. Previously at ARM and Huawei's Kirin team. Deep power-efficiency AI expertise.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/nawaf-alrashid-embedded",
  },
  {
    name: "Hisham Al-Hamdan",
    email: "h.hamdan@gmail.com",
    currentRole: "Senior Hardware AI Architect",
    currentCompany: "Samsung Research — Gulf",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 13,
    specialty: "AI Chip Architecture / ASIC",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Samsung", "MediaTek", "SDAIA"],
    skills: ["Chip micro-architecture", "Exynos NPU", "RTL design", "DFT", "power estimation", "SystemVerilog", "TSMC 4nm experience", "dataflow optimisation"],
    education: "PhD Microelectronics — University of Michigan",
    languages: ["Arabic", "English", "Korean (conversational)"],
    notes: "13 years chip design. Spent 6 years at Samsung in South Korea on Exynos NPU architecture, then transferred to Riyadh office. Previously at MediaTek AI chip team. PhD on sparse matrix accelerators. SDAIA advisory board member for AI hardware.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/hisham-alhamdan-asic",
  },
  {
    name: "Hamad Al-Ajmi",
    email: "hamad.ajmi@gmail.com",
    currentRole: "Hardware AI Engineer",
    currentCompany: "Qualcomm — KSA Innovation Centre",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 8,
    specialty: "AI Hardware / Edge Inference",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Qualcomm", "Arm", "STC"],
    skills: ["QNN SDK", "TensorFlow Lite", "C++", "ARM Cortex-M", "CMSIS-NN", "model pruning", "hardware benchmarking", "Android HAL"],
    education: "MSc Computer Engineering — King Abdullah University",
    languages: ["Arabic", "English"],
    notes: "8 years hardware AI. Qualcomm's edge-AI benchmark lead for MENA. Previously at Arm Cambridge on Cortex-M ML extensions. Holds Qualcomm AI Developer Certification (Expert). Regular contributor to TFLite open-source delegates.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/hamad-alajmi-hw",
  },
  // ── Senior / Research ────────────────────────────────────────────────────────
  {
    name: "Yazeed Al-Subaie",
    email: "yazeed.subaie@gmail.com",
    currentRole: "Director of AI Research",
    currentCompany: "SDAIA — Saudi Data and AI Authority",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 14,
    specialty: "AI Research / National AI Strategy",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["SDAIA", "DeepMind (visiting)", "Google Brain (fellowship)", "IBM Research"],
    skills: ["reinforcement learning", "AI governance", "federated learning", "model safety", "Arabic AI", "Python", "Julia", "research leadership"],
    education: "PhD Artificial Intelligence — University of Oxford",
    languages: ["Arabic", "English", "French"],
    notes: "14 years in AI research. Founding member of SDAIA, now Director of AI Research. Visiting researcher at DeepMind London 2021-22. PhD Oxford. Published 24 peer-reviewed papers. Chairman of the KSA AI Safety Working Group. One of Vision 2030's key AI architects.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/yazeed-alsubaie-sdaia",
  },
  {
    name: "Faris Al-Tamimi",
    email: "faris.tamimi@outlook.com",
    currentRole: "AI Research Scientist",
    currentCompany: "Alibaba Cloud DAMO Academy — Riyadh",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 7,
    specialty: "Computer Vision / Generative AI",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Alibaba", "Scale AI", "Thiqah"],
    skills: ["Stable Diffusion", "GAN", "PyTorch", "distributed training", "Python", "image generation", "video AI", "Chinese AI frameworks"],
    education: "MSc AI — National University of Singapore",
    languages: ["Arabic", "English", "Mandarin"],
    notes: "7 years in generative AI and computer vision. At Alibaba DAMO Academy's Riyadh hub working on multimodal models for Arabic content. Previously at Scale AI as data curator and at Thiqah (Saudi AI). Fluent Mandarin after 2 years in Hangzhou.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/faris-altamimi-gen-ai",
  },
  {
    name: "Nasser Al-Enezi",
    email: "nasser.enezi@gmail.com",
    currentRole: "Computer Vision Engineer",
    currentCompany: "stc Digital — Riyadh",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 5,
    specialty: "Computer Vision / Surveillance AI",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["stc", "Huawei", "SenseTime"],
    skills: ["YOLOv8", "DeepSORT", "Python", "OpenCV", "TensorRT", "RTSP streaming", "Redis", "FastAPI"],
    education: "BSc Software Engineering — Imam Muhammad ibn Saud University",
    languages: ["Arabic", "English"],
    notes: "5 years in computer vision for smart cities and telecom. At stc Digital building AI-powered network operations centre vision. Previously at Huawei and worked with SenseTime on a Vision 2030 smart-city project. Expert in real-time tracking systems.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/nasser-alenezi-cv",
  },
  {
    name: "Waleed Al-Yami",
    email: "waleed.alyami@gmail.com",
    currentRole: "Senior AI Engineer",
    currentCompany: "Palantir Technologies — KSA",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 9,
    specialty: "AI / Data Fusion / Decision Systems",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Palantir", "C3.ai", "Oracle AI"],
    skills: ["Foundry", "AIP", "Python", "Spark", "decision intelligence", "graph ML", "ontologies", "TypeScript", "data fusion"],
    education: "MSc Data Science — University of Edinburgh",
    languages: ["Arabic", "English"],
    notes: "9 years in enterprise AI. At Palantir as the technical lead for KSA government clients (MOI, MOH, MOMRA). Previously at C3.ai on predictive maintenance and Oracle AI. Deep ontology and graph ML background. Cleared for classified KSA government projects.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/waleed-alyami-palantir",
  },
  {
    name: "Sultan Al-Hajri",
    email: "sultan.hajri@gmail.com",
    currentRole: "Embedded Systems AI Engineer",
    currentCompany: "Lucidya AI — Riyadh",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 4,
    specialty: "Embedded AI / IoT",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["Lucidya", "STC", "Raspberry Pi Foundation (contributor)"],
    skills: ["TFLite Micro", "MicroPython", "C", "FreeRTOS", "ESP32", "Coral TPU", "Raspberry Pi", "sensor fusion", "Arabic IoT"],
    education: "BSc Electronics Engineering — Taibah University",
    languages: ["Arabic", "English"],
    notes: "4 years embedded AI. Built Lucidya's IoT data collection edge devices running on-device NLP for Arabic social sentiment. Open-source contributor to TFLite Micro. Young Saudi AI talent; winner of Saudi National AI Hackathon 2023.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/sultan-alhajri-embedded",
  },
  {
    name: "Saud Al-Harthy",
    email: "saud.harthy@gmail.com",
    currentRole: "AI Software Engineer",
    currentCompany: "ELM — Electronic Government Solutions",
    country: "Saudi Arabia", city: "Riyadh",
    yearsExperience: 3,
    specialty: "ML Engineering / Government AI",
    culturalBackground: "Arab/Saudi",
    hasAICompanyExp: true,
    aiCompanies: ["ELM", "stc"],
    skills: ["Python", "scikit-learn", "FastAPI", "Docker", "PostgreSQL", "REST APIs", "Arabic text classification", "data pipelines"],
    education: "BSc Computer Science — King Saud University (2021)",
    languages: ["Arabic", "English"],
    notes: "3 years at ELM (government tech company wholly owned by MOF). Built ML models for national ID fraud detection and Hajj crowd management AI. Fresh and fast-growing. Top performer in ELM's AI Graduate Programme 2021 cohort.",
    matchScore: null, stage: "sourced",
    linkedinUrl: "https://linkedin.com/in/saud-alharthy-elm",
  },
];

async function seed() {
  console.log("🌱  Seeding THINK-AI ATS...\n");

  // ── Jobs ──────────────────────────────────────────────────────────────────────
  console.log("📋  Creating jobs...");
  const createdJobs = [];
  for (const job of JOBS) {
    try {
      const existing = await prisma.hrJob.findFirst({ where: { title: job.title } });
      if (existing) {
        console.log(`  ⏭  Skipped (exists): ${job.title}`);
        createdJobs.push(existing);
        continue;
      }
      const created = await prisma.hrJob.create({ data: job });
      createdJobs.push(created);
      console.log(`  ✅  ${created.level}  ${created.title}`);
    } catch (e) {
      console.error(`  ❌  ${job.title}: ${e.message}`);
    }
  }

  // ── Candidates ────────────────────────────────────────────────────────────────
  console.log("\n👥  Creating candidates...");
  for (const candidate of CANDIDATES) {
    try {
      const existing = await prisma.hrCandidate.findFirst({ where: { email: candidate.email } });
      if (existing) {
        console.log(`  ⏭  Skipped (exists): ${candidate.name}`);
        continue;
      }
      const created = await prisma.hrCandidate.create({ data: candidate });
      console.log(`  ✅  ${created.name}  ·  ${created.currentRole}  ·  ${created.currentCompany}`);
    } catch (e) {
      console.error(`  ❌  ${candidate.name}: ${e.message}`);
    }
  }

  console.log(`\n✨  Seeding complete.`);
  console.log(`    Jobs created:       ${createdJobs.length}`);
  console.log(`    Candidates seeded:  ${CANDIDATES.length}`);
  console.log(`\n    Open ATS → http://localhost:3001/recruitment`);
}

seed()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
